extends:
  - "https://github.com/markormesher/tedium-config"

chores:
  - url: "https://github.com/markormesher/tedium-chores"
    branch: "mormesher/taskfile-chore"
    directory: "generate-taskfile"
