extends:
  - "https://github.com/markormesher/tedium-config"

chores:
  # overridden from the parent config
  - url: "https://github.com/markormesher/tedium-chores"
    directory: "generate-tasks-and-ci"
    environment:
      GO_RUNTIME_PACKAGES: "libgpgme-dev libbtrfs-dev"
      GO_RUNTIME_ENV_GOFLAGS: "-tags=remote"
