version: 2.1

defaults: &defaults
  working_directory: /tmp/app
  docker:
    - image: cimg/go:1.23.2

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ .Branch }}
            - go-mod-v1
      - run:
          name: Download dependencies
          command: go mod vendor
      - save_cache:
          key: go-mod-v1-{{ .Branch }}-{{ epoch }}
          paths:
            - vendor
      - persist_to_workspace:
          root: .
          paths:
            - .

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Lint
          command: make lint

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Install dependencies
          command: sudo apt update && sudo apt install -y --no-install-recommends libbtrfs-dev libgpgme-dev
      - run:
          name: Build
          command: make build

  publish:
    <<: *defaults
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build container image
          command: |
            docker build /tmp/app -f Containerfile -t ghcr.io/markormesher/${CIRCLE_PROJECT_REPONAME}:$(git describe --tags)
            docker image ls
      - run:
          name: Maybe publish container image
          command: |
            if ! git describe --exact-match HEAD > /dev/null 2>&1; then echo "Not on tagged commit - nothing to do"; exit 0; fi
            docker tag ghcr.io/markormesher/${CIRCLE_PROJECT_REPONAME}:$(git describe --tags) ghcr.io/markormesher/${CIRCLE_PROJECT_REPONAME}:latest
            echo "${GHCR_PUBLISH_TOKEN}" | docker login ghcr.io -u markormesher --password-stdin
            docker push ghcr.io/markormesher/${CIRCLE_PROJECT_REPONAME}:$(git describe --tags)
            docker push ghcr.io/markormesher/${CIRCLE_PROJECT_REPONAME}:latest

workflows:
  version: 2
  main:
    jobs:
      - setup:
          filters:
            tags:
              only: /.*/
      - lint:
          requires:
            - setup
          filters:
            tags:
              only: /.*/
      - build:
          requires:
            - setup
          filters:
            tags:
              only: /.*/
      - publish:
          requires:
            - lint
            - build
          filters:
            tags:
              only: /.*/
